Controllers/AmigosController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmprestimoJogos.Models;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoJogos.Controllers
{
    public class AmigosController : Controller
    {

        private readonly EmprestimoJogosContext _context;

        public AmigosController(EmprestimoJogosContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Amigo.ToListAsync());
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar([Bind("AmigoID, Nome")] Amigo amigo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(amigo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(amigo);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo.SingleOrDefaultAsync(m => m.AmigoID == id);
            if (amigo == null)
            {
                return NotFound();
            }
            return View(amigo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int AmigoID, [Bind("AmigoID, Nome")] Amigo amigo)
        {
            if (AmigoID != amigo.AmigoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(amigo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExisteAmigo(amigo.AmigoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(amigo);
        }

        public async Task<IActionResult> Remover(int id)
        {
            if (ExisteAmigo(id))
            {
                var amigo = await _context.Amigo.SingleOrDefaultAsync(m => m.AmigoID == id);
                _context.Amigo.Remove(amigo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } else {
                return NotFound();
            }
        }

        private bool ExisteAmigo(int id)
        {
            return _context.Amigo.Any(e => e.AmigoID == id);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JogosController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmprestimoJogos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace EmprestimoJogos.Controllers
{
    public class JogosController : Controller
    {

        private readonly EmprestimoJogosContext _context;

        public JogosController(EmprestimoJogosContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var jogos = from jogo in _context.Jogo
                        join amigo in _context.Amigo on jogo.AmigoID equals amigo.AmigoID into ja
                        from subq in ja.DefaultIfEmpty()
                        select new Jogo
                        {
                            JogoID = jogo.JogoID,
                            Nome = jogo.Nome,
                            NomeAmigo = subq.Nome
                        };

            return View(jogos);

        }

        private void ToList()
        {
            throw new NotImplementedException();
        }

        public IActionResult Adicionar()
        {
            PopularAmigosDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar([Bind("JogoID, Nome, AmigoID")] Jogo jogo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jogo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jogo);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogo.SingleOrDefaultAsync(m => m.JogoID == id);
            if (jogo == null)
            {
                return NotFound();
            }
            PopularAmigosDropDownList(jogo);
            return View(jogo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int JogoID, [Bind("JogoID, Nome, AmigoID")] Jogo jogo)
        {
            if (JogoID != jogo.JogoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExisteJogo(jogo.JogoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jogo);
        }

        public async Task<IActionResult> Remover(int id)
        {
            if (ExisteJogo(id))
            {
                var jogo = await _context.Jogo.SingleOrDefaultAsync(m => m.JogoID == id);
                _context.Jogo.Remove(jogo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        private bool ExisteJogo(int id)
        {
            return _context.Jogo.Any(e => e.JogoID == id);
        }

        private void PopularAmigosDropDownList(object selectedAmigo = null)
        {
            var amigosQuery = from a in _context.Amigo
                                   orderby a.Nome
                                   select a;
            ViewBag.AmigoID = new SelectList(amigosQuery.AsNoTracking(), "AmigoID", "Nome", selectedAmigo);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmprestimoJogos.Models;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoJogos.Controllers
{
    public class LoginController : Controller
    {
        private readonly EmprestimoJogosContext _context;

        public LoginController(EmprestimoJogosContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logar([Bind("Login, Senha")] Usuario usuario)
        {
            var usuario_valido = await _context.Usuario.SingleOrDefaultAsync(l => l.Login == usuario.Login && l.Senha == usuario.Senha);
            if (usuario_valido == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Empréstimo de Jogos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bulma/bulma.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bulma/bulma.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
</head>
<body>
    <!-- START NAV -->
    <nav class="navbar is-white">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item brand-text" asp-controller="Home" asp-action="Index">Empréstimo de Jogos</a>
                <div class="navbar-burger burger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="./">Sair</a>
                </div>
            </div>
        </div>
    </nav>
    <!-- END NAV -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Empréstimo de Jogos</p>
        </footer>
    </div>
</body>
</html>

Views/Shared/_Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Empréstimo de Jogos</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bulma/bulma.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bulma/bulma.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    </environment>
    @RenderBody()
</head>

Views/Shared/_Menu.cshtml
<div class="column is-3">
    <aside class="menu">
        <p class="menu-label">
            Administração
        </p>
        <ul class="menu-list">
            <li><a asp-controller="Amigos" asp-action="Index">Amigos</a></li>
            <li><a asp-controller="Jogos" asp-action="Index">Jogos</a></li>
            <li><a asp-controller="AmigosJogos" asp-action="Index">Amigos x Jogos</a></li>
        </ul>
    </aside>
</div>
@RenderBody()